version : '3'
services :
    db:
        container_name: db
        image: postgres:10.16
        environment:
            POSTGRES_USER : hamonize
            POSTGRES_PASSWORD : password
            POSTGRES_DB : hamonize_center
            TZ : "Asia/Seoul"
        ports:
            - "5432:5432"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - psql-data:/var/lib/postgresql/data
        restart: always
 
    web:
        container_name: web
        build: .
        volumes:
            - was-logs:/usr/local/tomcat/logs
            - ./uploads:/root/uploads       
        ports:
            - "8080:8080"
        environment:
            TZ : "Asia/Seoul"
        restart: always

    openldap:
        container_name: openldap
        image: jullee96/openldap:1.3      
        hostname: "ldap-server"
        ports:            
            - "389:389"
            - "636:636"
        environment:
            LDAP_OPENLDAP_GID: 1000
            LDAP_OPENLDAP_UID: 1000
            LDAP_LOG_LEVEL: "256"
            LDAP_TLS: "false"
            LDAP_DOMAIN: hamonize.com
            LDAP_BASE_DN: dc=hamonize,dc=com
            LDAP_ADMIN_PASSWORD: admin
            LDAP_ORGANISATION: invesume
        volumes:
            - ldap-data:/var/lib/ldap
            - ldap-conf:/etc/ldap/slapd.d              
        domainname: "hamonize.com"
        restart: always

    phpldapadmin:
        container_name: phpldapadmin
        image: osixia/phpldapadmin:latest
        ports:
            - "80:80"
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=openldap
            - PHPLDAPADMIN_HTTPS="false"
        links:
            - openldap
        depends_on:
            - openldap
        restart: always

    influxdb:
        container_name: influxdb
        image: influxdb:1.0
        ports:
          - "8083:8083"
          - "8086:8086"
          - "25826:25826/udp"
        volumes:
          - influxdb:/var/lib/influxdb
          - ./influxdb.conf:/etc/influxdb/influxdb.conf
          - ./types.db:/usr/share/collectd/types.db:ro
        restart: always

    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        ports:
          - "3000:3000"
        volumes:
          - grafana:/var/lib/grafana
          - ./grafana/plugins:/var/lib/grafana/plugins
          - ./grafana.ini:/etc/grafana/grafana.ini
          - ./grafana/provisioning:/etc/grafana/provisioning        
        restart: always     

           
volumes:
    hamonize_center.sql:
    psql-data:
    influxdb:
    grafana:
    was-logs:
    ldap-data:
    ldap-conf:
    was-logs:
